#!/usr/bin/env python3
"""
Generate llamaverse animal species, pets, and shelter content.
Llamas are the apex species. These are their beloved companions and pets.
Animals range from the microscopic to the gigantic — all ~800 documented
species kept by llamas as pets.
"""
import json, os, random, uuid
random.seed(42)

BASE = os.path.join(
    os.path.dirname(os.path.abspath(__file__)),
    "src/main/ml-data/cleverllamas/llamaverse/content"
)

# ─────────────────────────────────────────────────────────────────────────────
# ANIMAL SPECIES — full taxonomy + llamaverse pet context
# sizeClass: microscopic | tiny | small | medium | large | gigantic
# ─────────────────────────────────────────────────────────────────────────────
SPECIES = [
  # ── MICROSCOPIC ─────────────────────────────────────────────────────────────
  {"commonName":"Water Bear","sizeClass":"microscopic","fluffiness":1,"typicalDisposition":"indestructible","typicalLifespanYears":2,"classification":{"kingdom":"Animalia","phylum":"Tardigrada","class":"Eutardigrada","order":"Parachela","family":"Ramazzottiidae","genus":"Ramazzottius","species":"Ramazzottius oberhaeuseri"},"description":"Nearly impossible to kill. Survives vacuum, radiation, and the inside of Aaron's chess bag. Popular with llamas who want a pet that requires zero effort."},
  {"commonName":"Rotifer","sizeClass":"microscopic","fluffiness":1,"typicalDisposition":"frantic","typicalLifespanYears":1,"classification":{"kingdom":"Animalia","phylum":"Rotifera","class":"Bdelloidea","order":"Adinetida","family":"Adinetidae","genus":"Adineta","species":"Adineta vaga"},"description":"Spins its wheel-like feeding apparatus at astonishing speed. Llamas find them meditative to observe under a microscope."},
  {"commonName":"Nematode","sizeClass":"microscopic","fluffiness":1,"typicalDisposition":"relentless","typicalLifespanYears":1,"classification":{"kingdom":"Animalia","phylum":"Nematoda","class":"Chromadorea","order":"Rhabditida","family":"Rhabditidae","genus":"Caenorhabditis","species":"Caenorhabditis elegans"},"description":"Has exactly 959 cells. Llama scientists know each one by name. A firm favourite with biologist llamas."},
  {"commonName":"Sea Sparkle","sizeClass":"microscopic","fluffiness":1,"typicalDisposition":"luminous","typicalLifespanYears":1,"classification":{"kingdom":"Animalia","phylum":"Dinoflagellata","class":"Noctiluciphyceae","order":"Noctilucales","family":"Noctilucaceae","genus":"Noctiluca","species":"Noctiluca scintillans"},"description":"Bioluminescent single-celled organism. Llamas keep entire tanks of them in darkened rooms for parties."},
  {"commonName":"Copepod","sizeClass":"microscopic","fluffiness":1,"typicalDisposition":"hyperactive","typicalLifespanYears":1,"classification":{"kingdom":"Animalia","phylum":"Arthropoda","class":"Copepoda","order":"Calanoida","family":"Calanidae","genus":"Calanus","species":"Calanus finmarchicus"},"description":"The most abundant animal on earth and the first choice for llamas who want to feel cosmopolitan. Kept by the billion."},
  {"commonName":"Dust Mite","sizeClass":"microscopic","fluffiness":2,"typicalDisposition":"secretive","typicalLifespanYears":1,"classification":{"kingdom":"Animalia","phylum":"Arthropoda","class":"Arachnida","order":"Sarcoptiformes","family":"Pyroglyphidae","genus":"Dermatophagoides","species":"Dermatophagoides pteronyssinus"},"description":"Technically already living with most llamas whether invited or not. The forward-thinking llama simply chooses to consider them pets."},
  {"commonName":"Freshwater Hydra","sizeClass":"microscopic","fluffiness":1,"typicalDisposition":"regenerative","typicalLifespanYears":99,"classification":{"kingdom":"Animalia","phylum":"Cnidaria","class":"Hydrozoa","order":"Anthoathecata","family":"Hydridae","genus":"Hydra","species":"Hydra vulgaris"},"description":"Biologically immortal under the right conditions. A symbol of hope for llamas approaching middle age."},
  {"commonName":"Ostracod","sizeClass":"microscopic","fluffiness":1,"typicalDisposition":"private","typicalLifespanYears":1,"classification":{"kingdom":"Animalia","phylum":"Arthropoda","class":"Ostracoda","order":"Podocopida","family":"Cyprididae","genus":"Cypris","species":"Cypris pubera"},"description":"A tiny crustacean that lives inside a hinged shell. Llamas appreciate its commitment to having good boundaries."},
  {"commonName":"Bdelloid Rotifer","sizeClass":"microscopic","fluffiness":1,"typicalDisposition":"ancient","typicalLifespanYears":1,"classification":{"kingdom":"Animalia","phylum":"Rotifera","class":"Bdelloidea","order":"Philodinida","family":"Philodinidae","genus":"Philodina","species":"Philodina roseola"},"description":"Has not had sex in 80 million years and is doing perfectly fine. An inspiration to ascetic llamas everywhere."},
  {"commonName":"Vorticella","sizeClass":"microscopic","fluffiness":1,"typicalDisposition":"springy","typicalLifespanYears":1,"classification":{"kingdom":"Animalia","phylum":"Ciliophora","class":"Oligohymenophorea","order":"Sessilida","family":"Vorticellidae","genus":"Vorticella","species":"Vorticella convallaria"},"description":"Extends and retracts on a coiled stalk with alarming speed. Llamas find the motion deeply satisfying."},

  # ── TINY INVERTEBRATES ───────────────────────────────────────────────────────
  {"commonName":"Dwarf Cherry Shrimp","sizeClass":"tiny","fluffiness":1,"typicalDisposition":"industrious","typicalLifespanYears":2,"classification":{"kingdom":"Animalia","phylum":"Arthropoda","class":"Malacostraca","order":"Decapoda","family":"Atyidae","genus":"Neocaridina","species":"Neocaridina davidi"},"description":"Cherry-red. Constantly cleaning. Llamas admire their work ethic enormously."},
  {"commonName":"Crystal Red Shrimp","sizeClass":"tiny","fluffiness":1,"typicalDisposition":"delicate","typicalLifespanYears":2,"classification":{"kingdom":"Animalia","phylum":"Arthropoda","class":"Malacostraca","order":"Decapoda","family":"Atyidae","genus":"Caridina","species":"Caridina cantonensis"},"description":"A show-quality shrimp with red and white banding. Llamas enter them in national competitions."},
  {"commonName":"Amano Shrimp","sizeClass":"tiny","fluffiness":1,"typicalDisposition":"hardworking","typicalLifespanYears":3,"classification":{"kingdom":"Animalia","phylum":"Arthropoda","class":"Malacostraca","order":"Decapoda","family":"Atyidae","genus":"Caridina","species":"Caridina multidentata"},"description":"The most competent algae cleaner in the llamaverse aquarium hobby. Holds several records."},
  {"commonName":"Giant African Land Snail","sizeClass":"small","fluffiness":1,"typicalDisposition":"deliberate","typicalLifespanYears":10,"classification":{"kingdom":"Animalia","phylum":"Mollusca","class":"Gastropoda","order":"Stylommatophora","family":"Achatinidae","genus":"Achatina","species":"Achatina fulica"},"description":"Up to 30cm long with a magnificent spiralled shell. Llamas enjoy the meditative pace of snail-keeping."},
  {"commonName":"Garden Snail","sizeClass":"tiny","fluffiness":1,"typicalDisposition":"philosophical","typicalLifespanYears":7,"classification":{"kingdom":"Animalia","phylum":"Mollusca","class":"Gastropoda","order":"Stylommatophora","family":"Helicidae","genus":"Helix","species":"Helix aspersa"},"description":"Has been writing a very slow memoir for four years. Llamas await it eagerly."},
  {"commonName":"Blue-ringed Octopus","sizeClass":"tiny","fluffiness":1,"typicalDisposition":"dramatic","typicalLifespanYears":2,"classification":{"kingdom":"Animalia","phylum":"Mollusca","class":"Cephalopoda","order":"Octopoda","family":"Octopodidae","genus":"Hapalochlaena","species":"Hapalochlaena lunulata"},"description":"Highly venomous and extremely beautiful. Llamas who keep them are considered either very brave or very silly."},
  {"commonName":"Harlequin Shrimp","sizeClass":"tiny","fluffiness":1,"typicalDisposition":"theatrical","typicalLifespanYears":3,"classification":{"kingdom":"Animalia","phylum":"Arthropoda","class":"Malacostraca","order":"Decapoda","family":"Hymenoceridae","genus":"Hymenocera","species":"Hymenocera picta"},"description":"Polka-dotted predator of starfish. Llamas find its pattern more interesting than most art."},
  {"commonName":"Peacock Mantis Shrimp","sizeClass":"small","fluffiness":1,"typicalDisposition":"violent","typicalLifespanYears":6,"classification":{"kingdom":"Animalia","phylum":"Arthropoda","class":"Malacostraca","order":"Stomatopoda","family":"Odontodactylidae","genus":"Odontodactylus","species":"Odontodactylus scyllarus"},"description":"Punches with the force of a bullet. Has 16 types of colour receptors. Llamas keep them in reinforced tanks and treat them with absolute respect."},
  {"commonName":"Christmas Tree Worm","sizeClass":"tiny","fluffiness":3,"typicalDisposition":"shy","typicalLifespanYears":10,"classification":{"kingdom":"Animalia","phylum":"Annelida","class":"Polychaeta","order":"Sabellida","family":"Serpulidae","genus":"Spirobranchus","species":"Spirobranchus giganteus"},"description":"Retractable spiral plumes in vivid colours. Disappears the instant anything approaches. Llamas find this relatable."},
  {"commonName":"Velvet Worm","sizeClass":"tiny","fluffiness":4,"typicalDisposition":"ancient","typicalLifespanYears":6,"classification":{"kingdom":"Animalia","phylum":"Onychophora","class":"Udeonychophora","order":"Euonychophora","family":"Peripatopsidae","genus":"Peripatopsis","species":"Peripatopsis capensis"},"description":"An evolutionary holdover from 500 million years ago. Shoots slime. Llamas consider it a living history lesson."},
  {"commonName":"Horseshoe Crab","sizeClass":"medium","fluffiness":1,"typicalDisposition":"ancient","typicalLifespanYears":25,"classification":{"kingdom":"Animalia","phylum":"Arthropoda","class":"Merostomata","order":"Xiphosura","family":"Limulidae","genus":"Limulus","species":"Limulus polyphemus"},"description":"450 million years old and barely changed. Its blue blood saves lives. Llamas keep it in large saltwater pools and speak to it with reverence."},
  {"commonName":"Giant Isopod","sizeClass":"medium","fluffiness":1,"typicalDisposition":"stoic","typicalLifespanYears":5,"classification":{"kingdom":"Animalia","phylum":"Arthropoda","class":"Malacostraca","order":"Isopoda","family":"Cirolanidae","genus":"Bathynomus","species":"Bathynomus giganteus"},"description":"Deep-sea woodlouse, 50cm long. Looks mildly displeased at all times. Llamas feel seen."},
  {"commonName":"Goliath Birdeater Tarantula","sizeClass":"medium","fluffiness":6,"typicalDisposition":"territorial","typicalLifespanYears":25,"classification":{"kingdom":"Animalia","phylum":"Arthropoda","class":"Arachnida","order":"Araneae","family":"Theraphosidae","genus":"Theraphosa","species":"Theraphosa blondi"},"description":"The world's largest spider. Its leg span exceeds 30cm. Llamas keep them as a status symbol and a conversation starter."},
  {"commonName":"Giant Millipede","sizeClass":"small","fluffiness":2,"typicalDisposition":"gentle","typicalLifespanYears":7,"classification":{"kingdom":"Animalia","phylum":"Arthropoda","class":"Diplopoda","order":"Spirostreptida","family":"Spirostreptidae","genus":"Archispirostreptus","species":"Archispirostreptus gigas"},"description":"30cm of gentle, slow-moving legs. Llamas find petting them across all 400 legs unexpectedly soothing."},
  {"commonName":"Stick Insect","sizeClass":"small","fluffiness":1,"typicalDisposition":"invisible","typicalLifespanYears":3,"classification":{"kingdom":"Animalia","phylum":"Arthropoda","class":"Insecta","order":"Phasmatodea","family":"Phasmatidae","genus":"Phasma","species":"Phasma gigas"},"description":"Masters of disguise. Llamas frequently lose track of them and then rediscover them weeks later on a bookshelf, utterly unbothered."},
  {"commonName":"Leaf Insect","sizeClass":"tiny","fluffiness":1,"typicalDisposition":"cryptic","typicalLifespanYears":2,"classification":{"kingdom":"Animalia","phylum":"Arthropoda","class":"Insecta","order":"Phasmatodea","family":"Phylliidae","genus":"Phyllium","species":"Phyllium giganteum"},"description":"Indistinguishable from a leaf at any distance. Angela keeps twelve of them and can find eleven at any given time."},
  {"commonName":"Bombardier Beetle","sizeClass":"tiny","fluffiness":1,"typicalDisposition":"defensive","typicalLifespanYears":2,"classification":{"kingdom":"Animalia","phylum":"Arthropoda","class":"Insecta","order":"Coleoptera","family":"Carabidae","genus":"Brachinus","species":"Brachinus crepitans"},"description":"Fires a boiling chemical spray from its abdomen. Llamas keep them in sealed terrariums with great respect."},
  {"commonName":"Glow-worm","sizeClass":"tiny","fluffiness":1,"typicalDisposition":"luminous","typicalLifespanYears":2,"classification":{"kingdom":"Animalia","phylum":"Arthropoda","class":"Insecta","order":"Coleoptera","family":"Lampyridae","genus":"Lampyris","species":"Lampyris noctiluca"},"description":"The female glows green to attract mates, never moving. Llamas use colonies of them as ambient garden lighting."},
  {"commonName":"Hissing Cockroach","sizeClass":"small","fluffiness":1,"typicalDisposition":"theatrical","typicalLifespanYears":5,"classification":{"kingdom":"Animalia","phylum":"Arthropoda","class":"Insecta","order":"Blattodea","family":"Blaberidae","genus":"Gromphadorhina","species":"Gromphadorhina portentosa"},"description":"Hisses loudly when disturbed. Llamas find the sound deeply satisfying and keep groups of them as ambient noise machines."},
  {"commonName":"Praying Mantis","sizeClass":"small","fluffiness":1,"typicalDisposition":"meditative","typicalLifespanYears":1,"classification":{"kingdom":"Animalia","phylum":"Arthropoda","class":"Insecta","order":"Mantodea","family":"Mantidae","genus":"Mantis","species":"Mantis religiosa"},"description":"Looks perpetually deep in thought. Llamas who practice meditation consider the mantis a spiritual companion."},
  {"commonName":"Emperor Scorpion","sizeClass":"small","fluffiness":1,"typicalDisposition":"imperious","typicalLifespanYears":8,"classification":{"kingdom":"Animalia","phylum":"Arthropoda","class":"Arachnida","order":"Scorpiones","family":"Scorpionidae","genus":"Pandinus","species":"Pandinus imperator"},"description":"The largest scorpion in the world and, despite appearances, relatively mild-mannered. Llamas consider them misunderstood."},
  {"commonName":"Vinegaroon","sizeClass":"small","fluffiness":1,"typicalDisposition":"mysterious","typicalLifespanYears":7,"classification":{"kingdom":"Animalia","phylum":"Arthropoda","class":"Arachnida","order":"Thelyphonida","family":"Thelyphonidae","genus":"Mastigoproctus","species":"Mastigoproctus giganteus"},"description":"Sprays acetic acid from its tail. Not actually venomous but very convincingly terrifying. Llamas keep them to impress guests."},

  # ── AQUATIC ──────────────────────────────────────────────────────────────────
  {"commonName":"Axolotl","sizeClass":"small","fluffiness":3,"typicalDisposition":"serene","typicalLifespanYears":15,"classification":{"kingdom":"Animalia","phylum":"Chordata","class":"Amphibia","order":"Urodela","family":"Ambystomatidae","genus":"Ambystoma","species":"Ambystoma mexicanum"},"description":"Never fully metamorphoses. Keeps its feathery external gills forever. Llamas find this deeply relatable — why change when you're already perfect?"},
  {"commonName":"Coelacanth","sizeClass":"large","fluffiness":1,"typicalDisposition":"ancient","typicalLifespanYears":60,"classification":{"kingdom":"Animalia","phylum":"Chordata","class":"Actinistia","order":"Coelacanthiformes","family":"Latimeriidae","genus":"Latimeria","species":"Latimeria chalumnae"},"description":"A fish from 400 million years ago, still living. Requires a very deep and expensive tank. Owned by only four llamas in the llamaverse, all of whom are absurdly wealthy."},
  {"commonName":"Blobfish","sizeClass":"small","fluffiness":1,"typicalDisposition":"resigned","typicalLifespanYears":100,"classification":{"kingdom":"Animalia","phylum":"Chordata","class":"Actinopterygii","order":"Scorpaeniformes","family":"Psychrolutidae","genus":"Psychrolutes","species":"Psychrolutes marcidus"},"description":"Looks depressed at sea-level pressure. Llamas see this as a personality trait and respond with compassion."},
  {"commonName":"Pufferfish","sizeClass":"small","fluffiness":4,"typicalDisposition":"anxious","typicalLifespanYears":10,"classification":{"kingdom":"Animalia","phylum":"Chordata","class":"Actinopterygii","order":"Tetraodontiformes","family":"Tetraodontidae","genus":"Tetraodon","species":"Tetraodon mbu"},"description":"Inflates dramatically when frightened. Llamas are instructed not to sneak up on them, a rule that is frequently tested."},
  {"commonName":"Leafy Sea Dragon","sizeClass":"small","fluffiness":3,"typicalDisposition":"ethereal","typicalLifespanYears":7,"classification":{"kingdom":"Animalia","phylum":"Chordata","class":"Actinopterygii","order":"Syngnathiformes","family":"Syngnathidae","genus":"Phycodurus","species":"Phycodurus eques"},"description":"The most beautiful fish in the llamaverse. Looks like an animated piece of seaweed. Llamas keep them in hushed, reverent tanks."},
  {"commonName":"Mandarin Dragonet","sizeClass":"tiny","fluffiness":1,"typicalDisposition":"flamboyant","typicalLifespanYears":5,"classification":{"kingdom":"Animalia","phylum":"Chordata","class":"Actinopterygii","order":"Gobiiformes","family":"Callionymidae","genus":"Synchiropus","species":"Synchiropus splendidus"},"description":"Electric blue and orange. The most colourful fish in the sea. Llamas keep them as living art installations."},
  {"commonName":"Nautilus","sizeClass":"small","fluffiness":1,"typicalDisposition":"ancient","typicalLifespanYears":20,"classification":{"kingdom":"Animalia","phylum":"Mollusca","class":"Cephalopoda","order":"Nautilida","family":"Nautilidae","genus":"Nautilus","species":"Nautilus pompilius"},"description":"A living fossil with a perfect spiral shell. Llamas admire its geometry and the fact that it has been minding its own business for 500 million years."},
  {"commonName":"Giant Pacific Octopus","sizeClass":"large","fluffiness":1,"typicalDisposition":"curious","typicalLifespanYears":5,"classification":{"kingdom":"Animalia","phylum":"Mollusca","class":"Cephalopoda","order":"Octopoda","family":"Enteroctopodidae","genus":"Enteroctopus","species":"Enteroctopus dofleini"},"description":"Arm span up to 6 metres. Can open jars, recognise individual llamas, and escape from any enclosure it finds uninteresting."},
  {"commonName":"Clownfish","sizeClass":"tiny","fluffiness":1,"typicalDisposition":"territorial","typicalLifespanYears":10,"classification":{"kingdom":"Animalia","phylum":"Chordata","class":"Actinopterygii","order":"Perciformes","family":"Pomacentridae","genus":"Amphiprion","species":"Amphiprion ocellaris"},"description":"Immune to anemone stings. All clownfish are born male; the dominant one becomes female. Llamas find this arrangement admirably practical."},
  {"commonName":"Mimic Octopus","sizeClass":"small","fluffiness":1,"typicalDisposition":"theatrical","typicalLifespanYears":1,"classification":{"kingdom":"Animalia","phylum":"Mollusca","class":"Cephalopoda","order":"Octopoda","family":"Octopodidae","genus":"Thaumoctopus","species":"Thaumoctopus mimicus"},"description":"Can impersonate over 15 other species. Llamas are never quite sure what they're looking at, which they find energising."},
  {"commonName":"Sea Otter","sizeClass":"medium","fluffiness":10,"typicalDisposition":"cheerful","typicalLifespanYears":15,"classification":{"kingdom":"Animalia","phylum":"Chordata","class":"Mammalia","order":"Carnivora","family":"Mustelidae","genus":"Enhydra","species":"Enhydra lutris"},"description":"The fluffiest marine mammal and the most universally beloved pet in the llamaverse. Holds hands with its companion while sleeping. Llamas find this unbearably sweet."},
  {"commonName":"Narwhal","sizeClass":"gigantic","fluffiness":2,"typicalDisposition":"regal","typicalLifespanYears":50,"classification":{"kingdom":"Animalia","phylum":"Chordata","class":"Mammalia","order":"Artiodactyla","family":"Monodontidae","genus":"Monodon","species":"Monodon monoceros"},"description":"Has a tusk up to 3 metres long used for sensing ocean temperature. Owned only by coastal llamas with exceptionally large private fjords."},
  {"commonName":"Pygmy Seahorse","sizeClass":"microscopic","fluffiness":2,"typicalDisposition":"shy","typicalLifespanYears":2,"classification":{"kingdom":"Animalia","phylum":"Chordata","class":"Actinopterygii","order":"Syngnathiformes","family":"Syngnathidae","genus":"Hippocampus","species":"Hippocampus bargibanti"},"description":"2cm long and nearly invisible against coral. Males carry the young. Llamas consider this species morally superior to most."},
  {"commonName":"Vampire Squid","sizeClass":"small","fluffiness":1,"typicalDisposition":"gothic","typicalLifespanYears":8,"classification":{"kingdom":"Animalia","phylum":"Mollusca","class":"Cephalopoda","order":"Vampyromorphida","family":"Vampyroteuthidae","genus":"Vampyroteuthis","species":"Vampyroteuthis infernalis"},"description":"Its scientific name translates to 'vampire squid from hell'. It is neither squid nor octopus. Llamas who keep them tend to have strong aesthetic opinions."},
  {"commonName":"Dumbo Octopus","sizeClass":"small","fluffiness":2,"typicalDisposition":"buoyant","typicalLifespanYears":3,"classification":{"kingdom":"Animalia","phylum":"Mollusca","class":"Cephalopoda","order":"Octopoda","family":"Opisthoteuthidae","genus":"Grimpoteuthis","species":"Grimpoteuthis boylei"},"description":"Flaps ear-like fins to swim. Looks like a cartoon. Lives at extreme depth. Llamas with submersibles keep them."},
  {"commonName":"Bioluminescent Jellyfish","sizeClass":"small","fluffiness":1,"typicalDisposition":"ethereal","typicalLifespanYears":1,"classification":{"kingdom":"Animalia","phylum":"Cnidaria","class":"Scyphozoa","order":"Rhizostomeae","family":"Mastigiidae","genus":"Mastigias","species":"Mastigias papua"},"description":"Glows blue in the dark. Llamas keep tanks of them in bedrooms as nightlights."},
  {"commonName":"Immortal Jellyfish","sizeClass":"microscopic","fluffiness":1,"typicalDisposition":"cyclical","typicalLifespanYears":99,"classification":{"kingdom":"Animalia","phylum":"Cnidaria","class":"Hydrozoa","order":"Anthoathecata","family":"Oceaniidae","genus":"Turritopsis","species":"Turritopsis dohrnii"},"description":"Can revert to its juvenile state when stressed. Technically immortal. Llamas keep them as philosophical objects."},
  {"commonName":"Giant Squid","sizeClass":"gigantic","fluffiness":1,"typicalDisposition":"elusive","typicalLifespanYears":5,"classification":{"kingdom":"Animalia","phylum":"Mollusca","class":"Cephalopoda","order":"Oegopsida","family":"Architeuthidae","genus":"Architeuthis","species":"Architeuthis dux"},"description":"Up to 13 metres long. Rarely seen alive. Three llamas claim to own one; two are lying."},

  # ── AMPHIBIANS ────────────────────────────────────────────────────────────────
  {"commonName":"Poison Dart Frog","sizeClass":"tiny","fluffiness":1,"typicalDisposition":"vibrant","typicalLifespanYears":10,"classification":{"kingdom":"Animalia","phylum":"Chordata","class":"Amphibia","order":"Anura","family":"Dendrobatidae","genus":"Dendrobates","species":"Dendrobates tinctorius"},"description":"Brilliantly coloured and lethal to touch. Llamas keep them behind glass and admire them from a respectful distance."},
  {"commonName":"Goliath Frog","sizeClass":"medium","fluffiness":1,"typicalDisposition":"sedentary","typicalLifespanYears":21,"classification":{"kingdom":"Animalia","phylum":"Chordata","class":"Amphibia","order":"Anura","family":"Conrauidae","genus":"Conraua","species":"Conraua goliath"},"description":"The world's largest frog at 3.3kg. Does not croak. Llamas find its silence powerful."},
  {"commonName":"Hellbender Salamander","sizeClass":"medium","fluffiness":1,"typicalDisposition":"ancient","typicalLifespanYears":30,"classification":{"kingdom":"Animalia","phylum":"Chordata","class":"Amphibia","order":"Urodela","family":"Cryptobranchidae","genus":"Cryptobranchus","species":"Cryptobranchus alleganiensis"},"description":"North America's largest salamander. Absorbs oxygen through its wrinkled skin. Llamas who keep them report unexpected feelings of calm."},
  {"commonName":"Glass Frog","sizeClass":"tiny","fluffiness":1,"typicalDisposition":"transparent","typicalLifespanYears":14,"classification":{"kingdom":"Animalia","phylum":"Chordata","class":"Amphibia","order":"Anura","family":"Centrolenidae","genus":"Hyalinobatrachium","species":"Hyalinobatrachium valerioi"},"description":"Its underside is completely transparent. You can see its beating heart. Llamas find this either beautiful or disturbing, usually both."},
  {"commonName":"Surinam Toad","sizeClass":"small","fluffiness":1,"typicalDisposition":"unusual","typicalLifespanYears":8,"classification":{"kingdom":"Animalia","phylum":"Chordata","class":"Amphibia","order":"Anura","family":"Pipidae","genus":"Pipa","species":"Pipa pipa"},"description":"Carries eggs embedded in its back skin. Young emerge by bursting through the skin. Llamas who research this before buying one frequently reconsider."},
  {"commonName":"Chinese Giant Salamander","sizeClass":"large","fluffiness":1,"typicalDisposition":"prehistoric","typicalLifespanYears":80,"classification":{"kingdom":"Animalia","phylum":"Chordata","class":"Amphibia","order":"Urodela","family":"Cryptobranchidae","genus":"Andrias","species":"Andrias davidianus"},"description":"The world's largest amphibian at 1.8 metres. Critically endangered and extremely old. Llamas with the appropriate permits treat ownership as a conservation duty."},
  {"commonName":"Red-eyed Tree Frog","sizeClass":"tiny","fluffiness":1,"typicalDisposition":"dramatic","typicalLifespanYears":5,"classification":{"kingdom":"Animalia","phylum":"Chordata","class":"Amphibia","order":"Anura","family":"Hylidae","genus":"Agalychnis","species":"Agalychnis callidryas"},"description":"Its vivid red eyes are designed to startle predators. Llamas have placed portraits of them in many public buildings."},
  {"commonName":"Olm","sizeClass":"small","fluffiness":1,"typicalDisposition":"pale","typicalLifespanYears":100,"classification":{"kingdom":"Animalia","phylum":"Chordata","class":"Amphibia","order":"Urodela","family":"Proteidae","genus":"Proteus","species":"Proteus anguinus"},"description":"Blind cave salamander, lives 100 years, never sees daylight. Llamas who keep them create specially darkened cave tanks and leave them entirely alone, which is apparently what the olm wants."},

  # ── REPTILES ──────────────────────────────────────────────────────────────────
  {"commonName":"Komodo Dragon","sizeClass":"large","fluffiness":1,"typicalDisposition":"patient","typicalLifespanYears":30,"classification":{"kingdom":"Animalia","phylum":"Chordata","class":"Reptilia","order":"Squamata","family":"Varanidae","genus":"Varanus","species":"Varanus komodoensis"},"description":"The world's largest lizard. Carries venomous saliva. Llamas who keep them note they are surprisingly good listeners."},
  {"commonName":"Galápagos Tortoise","sizeClass":"gigantic","fluffiness":1,"typicalDisposition":"venerable","typicalLifespanYears":177,"classification":{"kingdom":"Animalia","phylum":"Chordata","class":"Reptilia","order":"Testudines","family":"Testudinidae","genus":"Chelonoidis","species":"Chelonoidis niger"},"description":"Weighs up to 400kg and lives 177 years. A tortoise alive today hatched before MarkLogic existed. Llamas keep them for perspective."},
  {"commonName":"Chameleon","sizeClass":"small","fluffiness":1,"typicalDisposition":"changeable","typicalLifespanYears":10,"classification":{"kingdom":"Animalia","phylum":"Chordata","class":"Reptilia","order":"Squamata","family":"Chamaeleonidae","genus":"Chamaeleo","species":"Chamaeleo calyptratus"},"description":"Changes colour not for camouflage but to express mood. Llamas find this refreshingly honest."},
  {"commonName":"Satanic Leaf-tailed Gecko","sizeClass":"tiny","fluffiness":1,"typicalDisposition":"theatrical","typicalLifespanYears":5,"classification":{"kingdom":"Animalia","phylum":"Chordata","class":"Reptilia","order":"Squamata","family":"Gekkonidae","genus":"Uroplatus","species":"Uroplatus phantasticus"},"description":"Its name is accurate. Has red eyes and a leaf-shaped tail that makes it disappear against bark. Llamas appreciate the commitment to branding."},
  {"commonName":"Thorny Devil","sizeClass":"tiny","fluffiness":1,"typicalDisposition":"armoured","typicalLifespanYears":20,"classification":{"kingdom":"Animalia","phylum":"Chordata","class":"Reptilia","order":"Squamata","family":"Agamidae","genus":"Moloch","species":"Moloch horridus"},"description":"Channels dew from its skin to its mouth through capillary action. Llamas find this technically impressive. The spines are also notable."},
  {"commonName":"Frilled Lizard","sizeClass":"medium","fluffiness":1,"typicalDisposition":"theatrical","typicalLifespanYears":20,"classification":{"kingdom":"Animalia","phylum":"Chordata","class":"Reptilia","order":"Squamata","family":"Agamidae","genus":"Chlamydosaurus","species":"Chlamydosaurus kingii"},"description":"Fans out a large neck frill when threatened, then runs away on two legs. Llamas consider this the correct response to most situations."},
  {"commonName":"Green Iguana","sizeClass":"large","fluffiness":1,"typicalDisposition":"imperious","typicalLifespanYears":20,"classification":{"kingdom":"Animalia","phylum":"Chordata","class":"Reptilia","order":"Squamata","family":"Iguanidae","genus":"Iguana","species":"Iguana iguana"},"description":"Up to 2 metres long and profoundly unimpressed by everything. One of the most commonly kept large reptiles in the llamaverse."},
  {"commonName":"Blue-tongued Skink","sizeClass":"small","fluffiness":1,"typicalDisposition":"calm","typicalLifespanYears":20,"classification":{"kingdom":"Animalia","phylum":"Chordata","class":"Reptilia","order":"Squamata","family":"Scincidae","genus":"Tiliqua","species":"Tiliqua scincoides"},"description":"Has a vivid blue tongue it extends slowly when threatened. Llamas find the deliberate drama relatable."},
  {"commonName":"Armadillo Lizard","sizeClass":"tiny","fluffiness":1,"typicalDisposition":"defensive","typicalLifespanYears":25,"classification":{"kingdom":"Animalia","phylum":"Chordata","class":"Reptilia","order":"Squamata","family":"Cordylidae","genus":"Ouroborus","species":"Ouroborus cataphractus"},"description":"Rolls into a tight ball holding its own tail in its mouth. A living dragon symbol. Llamas who study philosophy keep them."},
  {"commonName":"Mata Mata Turtle","sizeClass":"medium","fluffiness":1,"typicalDisposition":"eccentric","typicalLifespanYears":75,"classification":{"kingdom":"Animalia","phylum":"Chordata","class":"Reptilia","order":"Testudines","family":"Chelidae","genus":"Chelus","species":"Chelus fimbriata"},"description":"Looks like a pile of leaves. Waits, motionless, for fish to swim past, then inhales them. Llamas admire its patience and aesthetic choices."},
  {"commonName":"Tuatara","sizeClass":"small","fluffiness":1,"typicalDisposition":"ancient","typicalLifespanYears":100,"classification":{"kingdom":"Animalia","phylum":"Chordata","class":"Reptilia","order":"Rhynchocephalia","family":"Sphenodontidae","genus":"Sphenodon","species":"Sphenodon punctatus"},"description":"The only surviving member of an order that diverged from other reptiles 240 million years ago. Has a third eye on top of its head. Llamas consider it the elder statesperson of the animal kingdom."},

  # ── BIRDS ─────────────────────────────────────────────────────────────────────
  {"commonName":"Barn Owl","sizeClass":"medium","fluffiness":7,"typicalDisposition":"nocturnal","typicalLifespanYears":25,"classification":{"kingdom":"Animalia","phylum":"Chordata","class":"Aves","order":"Strigiformes","family":"Tytonidae","genus":"Tyto","species":"Tyto alba"},"description":"The most widespread bird species on earth. Silent in flight. Rotates its head 270 degrees. Llamas find it intimidating in the best possible way."},
  {"commonName":"Snowy Owl","sizeClass":"medium","fluffiness":10,"typicalDisposition":"regal","typicalLifespanYears":25,"classification":{"kingdom":"Animalia","phylum":"Chordata","class":"Aves","order":"Strigiformes","family":"Strigidae","genus":"Bubo","species":"Bubo scandiacus"},"description":"White as fresh snow, yellow-eyed, and profoundly dignified. Llamas in the northern territories keep them as companions and they are worth every scrap of effort involved."},
  {"commonName":"Tawny Frogmouth","sizeClass":"small","fluffiness":5,"typicalDisposition":"disguised","typicalLifespanYears":14,"classification":{"kingdom":"Animalia","phylum":"Chordata","class":"Aves","order":"Podargiformes","family":"Podargidae","genus":"Podargus","species":"Podargus strigoides"},"description":"Not an owl. Freezes with its beak pointed up to look like a broken branch. Llamas find its commitment to the bit admirable."},
  {"commonName":"Shoebill Stork","sizeClass":"large","fluffiness":3,"typicalDisposition":"ancient","typicalLifespanYears":35,"classification":{"kingdom":"Animalia","phylum":"Chordata","class":"Aves","order":"Pelecaniformes","family":"Balaenicipitidae","genus":"Balaeniceps","species":"Balaeniceps rex"},"description":"Has a beak shaped like a dutch clog. Stares without blinking for hours. Makes a sound like a machine gun when greeting friends. Llamas find it mesmerising."},
  {"commonName":"Harpy Eagle","sizeClass":"large","fluffiness":5,"typicalDisposition":"imperious","typicalLifespanYears":35,"classification":{"kingdom":"Animalia","phylum":"Chordata","class":"Aves","order":"Accipitriformes","family":"Accipitridae","genus":"Harpia","species":"Harpia harpyja"},"description":"The most powerful eagle in the world. Talons the size of grizzly bear claws. Llamas who keep them have a special room and a very good falconry licence."},
  {"commonName":"Secretary Bird","sizeClass":"large","fluffiness":5,"typicalDisposition":"precise","typicalLifespanYears":19,"classification":{"kingdom":"Animalia","phylum":"Chordata","class":"Aves","order":"Accipitriformes","family":"Sagittariidae","genus":"Sagittarius","species":"Sagittarius serpentarius"},"description":"Stalks across grassland on long legs and stamps on snakes. Looks like it works in administration. Llamas in professional roles keep it as a spirit animal."},
  {"commonName":"Kakapo","sizeClass":"medium","fluffiness":8,"typicalDisposition":"oblivious","typicalLifespanYears":60,"classification":{"kingdom":"Animalia","phylum":"Chordata","class":"Aves","order":"Psittaciformes","family":"Strigopidae","genus":"Strigops","species":"Strigops habroptilus"},"description":"The world's largest parrot. Flightless. Nocturnal. Booms from hilltops to attract mates. Critically endangered. Llamas consider keeping one a conservation achievement of the highest order."},
  {"commonName":"Magnificent Frigatebird","sizeClass":"large","fluffiness":2,"typicalDisposition":"dramatic","typicalLifespanYears":25,"classification":{"kingdom":"Animalia","phylum":"Chordata","class":"Aves","order":"Suliformes","family":"Fregatidae","genus":"Fregata","species":"Fregata magnificens"},"description":"Males inflate a vast red throat pouch to attract females. Has a wingspan of 2.3 metres. Llamas who keep them require substantial outdoor space and a tolerance for theatre."},
  {"commonName":"Resplendent Quetzal","sizeClass":"small","fluffiness":7,"typicalDisposition":"elusive","typicalLifespanYears":25,"classification":{"kingdom":"Animalia","phylum":"Chordata","class":"Aves","order":"Trogoniformes","family":"Trogonidae","genus":"Pharomachrus","species":"Pharomachrus mocinno"},"description":"Considered the most beautiful bird in the world by several independent surveys. Its tail feathers are 1 metre long. Dies in captivity unless conditions are perfect. Llamas who succeed are deeply respected."},
  {"commonName":"Lyrebird","sizeClass":"medium","fluffiness":6,"typicalDisposition":"mimetic","typicalLifespanYears":30,"classification":{"kingdom":"Animalia","phylum":"Chordata","class":"Aves","order":"Passeriformes","family":"Menuridae","genus":"Menura","species":"Menura novaehollandiae"},"description":"Can perfectly mimic any sound it hears, including chain saws, camera shutters, and other llamas. Llamas keep them and are regularly unsettled by the results."},
  {"commonName":"Cassowary","sizeClass":"large","fluffiness":3,"typicalDisposition":"dangerous","typicalLifespanYears":40,"classification":{"kingdom":"Animalia","phylum":"Chordata","class":"Aves","order":"Casuariiformes","family":"Casuariidae","genus":"Casuarius","species":"Casuarius casuarius"},"description":"The most dangerous bird in the world. A 5cm dagger claw on each foot. Llamas who keep them do so in a very large enclosure and have signed extensive waivers."},
  {"commonName":"Atlantic Puffin","sizeClass":"small","fluffiness":6,"typicalDisposition":"cheerful","typicalLifespanYears":20,"classification":{"kingdom":"Animalia","phylum":"Chordata","class":"Aves","order":"Charadriiformes","family":"Alcidae","genus":"Fratercula","species":"Fratercula arctica"},"description":"A seabird with a vividly painted beak and a dignified waddle. Llamas near the coast keep small colonies. Watching them waddle is considered therapeutic."},
  {"commonName":"Macaroni Penguin","sizeClass":"small","fluffiness":5,"typicalDisposition":"rakish","typicalLifespanYears":20,"classification":{"kingdom":"Animalia","phylum":"Chordata","class":"Aves","order":"Sphenisciformes","family":"Spheniscidae","genus":"Eudyptes","species":"Eudyptes chrysolophus"},"description":"Has vivid orange crest feathers. Named after the 18th-century fashion trend. Llamas find the hat-like plumage irresistible."},
  {"commonName":"Hoatzin","sizeClass":"medium","fluffiness":4,"typicalDisposition":"punk","typicalLifespanYears":15,"classification":{"kingdom":"Animalia","phylum":"Chordata","class":"Aves","order":"Opisthocomiformes","family":"Opisthocomidae","genus":"Opisthocomus","species":"Opisthocomus hoazin"},"description":"Its chicks have claws on their wings like dinosaurs. Smells of manure due to its fermenting crop. Has a punk crest. Llamas who keep them are committed to the full experience."},
  {"commonName":"Bearded Vulture","sizeClass":"large","fluffiness":4,"typicalDisposition":"bone-obsessed","typicalLifespanYears":40,"classification":{"kingdom":"Animalia","phylum":"Chordata","class":"Aves","order":"Accipitriformes","family":"Accipitridae","genus":"Gypaetus","species":"Gypaetus barbatus"},"description":"Its entire diet is bones. Drops them from height onto rocks to crack them. Has orange-red plumage because it bathes in iron-rich mud on purpose. Llamas respect the level of intention."},

  # ── SMALL MAMMALS ────────────────────────────────────────────────────────────
  {"commonName":"Chinchilla","sizeClass":"small","fluffiness":10,"typicalDisposition":"erratic","typicalLifespanYears":15,"classification":{"kingdom":"Animalia","phylum":"Chordata","class":"Mammalia","order":"Rodentia","family":"Chinchillidae","genus":"Chinchilla","species":"Chinchilla lanigera"},"description":"Has the densest fur of any land animal. Jumps unexpectedly to great heights. Llamas find the chaos charming."},
  {"commonName":"Pygmy Slow Loris","sizeClass":"tiny","fluffiness":8,"typicalDisposition":"venomous","typicalLifespanYears":20,"classification":{"kingdom":"Animalia","phylum":"Chordata","class":"Mammalia","order":"Primates","family":"Lorisidae","genus":"Xanthonycticebus","species":"Xanthonycticebus pygmaeus"},"description":"The only venomous primate. Looks like a soft toy. Llamas who keep them are acutely aware of this contradiction."},
  {"commonName":"Star-nosed Mole","sizeClass":"tiny","fluffiness":4,"typicalDisposition":"sensory","typicalLifespanYears":5,"classification":{"kingdom":"Animalia","phylum":"Chordata","class":"Mammalia","order":"Eulipotyphla","family":"Talpidae","genus":"Condylura","species":"Condylura cristata"},"description":"22 tentacles around its nose containing 25,000 sensory receptors. Can detect and eat prey in under 120 milliseconds. Llamas find it admirable."},
  {"commonName":"Naked Mole Rat","sizeClass":"tiny","fluffiness":1,"typicalDisposition":"eusocial","typicalLifespanYears":32,"classification":{"kingdom":"Animalia","phylum":"Chordata","class":"Mammalia","order":"Rodentia","family":"Heterocephalidae","genus":"Heterocephalus","species":"Heterocephalus glaber"},"description":"Cannot feel pain in its skin. Is nearly cold-blooded. Lives in colonies with a queen. Is practically immune to cancer. Llamas study it for longevity tips."},
  {"commonName":"Aye-aye","sizeClass":"small","fluffiness":6,"typicalDisposition":"eccentric","typicalLifespanYears":23,"classification":{"kingdom":"Animalia","phylum":"Chordata","class":"Mammalia","order":"Primates","family":"Daubentoniidae","genus":"Daubentonia","species":"Daubentonia madagascariensis"},"description":"Has a long skeletal middle finger for tapping on wood and extracting grubs. Enormous eyes. Llamas find it fascinating and keep it in tall trees."},
  {"commonName":"Platypus","sizeClass":"small","fluffiness":7,"typicalDisposition":"improbable","typicalLifespanYears":17,"classification":{"kingdom":"Animalia","phylum":"Chordata","class":"Mammalia","order":"Monotremata","family":"Ornithorhynchidae","genus":"Ornithorhynchus","species":"Ornithorhynchus anatinus"},"description":"A venomous, duck-billed, egg-laying, electrosensing, semi-aquatic mammal. When first described to European scientists they assumed it was a hoax. Llamas find this attitude uncharitable."},
  {"commonName":"Pangolin","sizeClass":"medium","fluffiness":1,"typicalDisposition":"armoured","typicalLifespanYears":20,"classification":{"kingdom":"Animalia","phylum":"Chordata","class":"Mammalia","order":"Pholidota","family":"Manidae","genus":"Manis","species":"Manis pentadactyla"},"description":"The only mammal entirely covered in scales. Rolls into a ball when threatened. The most illegally trafficked animal in the human world, which llamas find unconscionable."},
  {"commonName":"Capybara","sizeClass":"large","fluffiness":4,"typicalDisposition":"serene","typicalLifespanYears":12,"classification":{"kingdom":"Animalia","phylum":"Chordata","class":"Mammalia","order":"Rodentia","family":"Caviidae","genus":"Hydrochoerus","species":"Hydrochoerus hydrochaeris"},"description":"The world's largest rodent. Universally liked by all other animals. Llamas consider the capybara the embodiment of good social energy. Very popular pets."},
  {"commonName":"Sugar Glider","sizeClass":"tiny","fluffiness":7,"typicalDisposition":"gliding","typicalLifespanYears":15,"classification":{"kingdom":"Animalia","phylum":"Chordata","class":"Mammalia","order":"Diprotodontia","family":"Petauridae","genus":"Petaurus","species":"Petaurus breviceps"},"description":"A palm-sized marsupial that glides between trees on skin membranes. Llamas who keep them report being occasionally startled by sudden airborne visits."},
  {"commonName":"African Pygmy Hedgehog","sizeClass":"tiny","fluffiness":3,"typicalDisposition":"nocturnal","typicalLifespanYears":5,"classification":{"kingdom":"Animalia","phylum":"Chordata","class":"Mammalia","order":"Eulipotyphla","family":"Erinaceidae","genus":"Atelerix","species":"Atelerix albiventris"},"description":"2000 spines on its back. Anointsitself with new scents by self-licking. Llamas find this habit eccentric but non-judgeable."},
  {"commonName":"Fennec Fox","sizeClass":"small","fluffiness":8,"typicalDisposition":"alert","typicalLifespanYears":14,"classification":{"kingdom":"Animalia","phylum":"Chordata","class":"Mammalia","order":"Carnivora","family":"Canidae","genus":"Vulpes","species":"Vulpes zerda"},"description":"Enormous ears relative to body size, used for heat dissipation and hearing prey underground. Weighs under 1kg. Llamas find it disproportionate in the best possible sense."},
  {"commonName":"Red Panda","sizeClass":"small","fluffiness":9,"typicalDisposition":"solitary","typicalLifespanYears":15,"classification":{"kingdom":"Animalia","phylum":"Chordata","class":"Mammalia","order":"Carnivora","family":"Ailuridae","genus":"Ailurus","species":"Ailurus fulgens"},"description":"Not a bear, not a raccoon. Fluffy. Eats bamboo. Wrist bone acts as a false thumb. Llamas regard it as the peak of casual animal excellence."},
  {"commonName":"Arctic Fox","sizeClass":"small","fluffiness":9,"typicalDisposition":"resourceful","typicalLifespanYears":14,"classification":{"kingdom":"Animalia","phylum":"Chordata","class":"Mammalia","order":"Carnivora","family":"Canidae","genus":"Vulpes","species":"Vulpes lagopus"},"description":"Changes coat from brown to white in winter. The densest fur of any arctic mammal. Llamas in cold regions keep them and the coat synchronisation is considered beautiful."},
  {"commonName":"Meerkat","sizeClass":"small","fluffiness":3,"typicalDisposition":"vigilant","typicalLifespanYears":12,"classification":{"kingdom":"Animalia","phylum":"Chordata","class":"Mammalia","order":"Carnivora","family":"Herpestidae","genus":"Suricata","species":"Suricata suricatta"},"description":"Immune to certain venoms. Takes turns standing guard. Llamas who keep groups of them report a significant improvement in household security awareness."},

  # ── LARGE / GIGANTIC MAMMALS ─────────────────────────────────────────────────
  {"commonName":"African Elephant","sizeClass":"gigantic","fluffiness":1,"typicalDisposition":"wise","typicalLifespanYears":70,"classification":{"kingdom":"Animalia","phylum":"Chordata","class":"Mammalia","order":"Proboscidea","family":"Elephantidae","genus":"Loxodonta","species":"Loxodonta africana"},"description":"The largest land animal on earth. Mourns its dead. Has a memory that spans decades. Llamas who keep them require extensive grounds and considerable humility."},
  {"commonName":"Pygmy Elephant","sizeClass":"large","fluffiness":1,"typicalDisposition":"gentle","typicalLifespanYears":50,"classification":{"kingdom":"Animalia","phylum":"Chordata","class":"Mammalia","order":"Proboscidea","family":"Elephantidae","genus":"Elephas","species":"Elephas maximus borneensis"},"description":"A dwarf subspecies of Asian elephant. Rounder face, longer tail, calmer disposition. Llamas consider it the approachable version of a great animal."},
  {"commonName":"Hippopotamus","sizeClass":"gigantic","fluffiness":1,"typicalDisposition":"unpredictable","typicalLifespanYears":45,"classification":{"kingdom":"Animalia","phylum":"Chordata","class":"Mammalia","order":"Artiodactyla","family":"Hippopotamidae","genus":"Hippopotamus","species":"Hippopotamus amphibius"},"description":"Secretes a natural sunscreen from its skin. Despite appearances, more closely related to whales than to pigs. Llamas keep them in very large ponds and maintain respectful distances."},
  {"commonName":"Pygmy Hippopotamus","sizeClass":"medium","fluffiness":1,"typicalDisposition":"secretive","typicalLifespanYears":42,"classification":{"kingdom":"Animalia","phylum":"Chordata","class":"Mammalia","order":"Artiodactyla","family":"Hippopotamidae","genus":"Choeropsis","species":"Choeropsis liberiensis"},"description":"Half the size of a standard hippo and considerably more manageable. More solitary. Llamas with appropriate space and permits keep them in forest gardens."},
  {"commonName":"Giraffe","sizeClass":"gigantic","fluffiness":2,"typicalDisposition":"serene","typicalLifespanYears":25,"classification":{"kingdom":"Animalia","phylum":"Chordata","class":"Mammalia","order":"Artiodactyla","family":"Giraffidae","genus":"Giraffa","species":"Giraffa camelopardalis"},"description":"The tallest animal on earth. Its heart weighs 11kg to pump blood up its neck. Llamas who keep giraffes require exceptional ceiling heights and look up to them in every sense."},
  {"commonName":"Okapi","sizeClass":"large","fluffiness":3,"typicalDisposition":"shy","typicalLifespanYears":20,"classification":{"kingdom":"Animalia","phylum":"Chordata","class":"Mammalia","order":"Artiodactyla","family":"Giraffidae","genus":"Okapia","species":"Okapia johnstoni"},"description":"Looks like a cross between a zebra and a giraffe. Its closest relative is the giraffe. Unknown to science until 1901. Llamas feel a kinship with animals that keep a low profile."},
  {"commonName":"White Rhinoceros","sizeClass":"gigantic","fluffiness":1,"typicalDisposition":"stoic","typicalLifespanYears":50,"classification":{"kingdom":"Animalia","phylum":"Chordata","class":"Mammalia","order":"Perissodactyla","family":"Rhinocerotidae","genus":"Ceratotherium","species":"Ceratotherium simum"},"description":"The second largest land animal. Near-sighted. Surprisingly fast. Its horn is made of keratin — essentially compressed wool. Llamas find this connection profound."},
  {"commonName":"Tapir","sizeClass":"large","fluffiness":2,"typicalDisposition":"gentle","typicalLifespanYears":30,"classification":{"kingdom":"Animalia","phylum":"Chordata","class":"Mammalia","order":"Perissodactyla","family":"Tapiridae","genus":"Tapirus","species":"Tapirus terrestris"},"description":"Has a prehensile snout it uses to grab leaves. An evolutionary holdover from 50 million years ago. Llamas find it endearingly unfashionable."},
  {"commonName":"Clouded Leopard","sizeClass":"medium","fluffiness":6,"typicalDisposition":"elusive","typicalLifespanYears":17,"classification":{"kingdom":"Animalia","phylum":"Chordata","class":"Mammalia","order":"Carnivora","family":"Felidae","genus":"Neofelis","species":"Neofelis nebulosa"},"description":"The longest canine teeth relative to body size of any living cat. Can rotate its ankles 180 degrees. Llamas who manage to keep them report the cats' presence as an excellent test of nerve."},
  {"commonName":"Snow Leopard","sizeClass":"large","fluffiness":9,"typicalDisposition":"secretive","typicalLifespanYears":21,"classification":{"kingdom":"Animalia","phylum":"Chordata","class":"Mammalia","order":"Carnivora","family":"Felidae","genus":"Panthera","species":"Panthera uncia"},"description":"Wraps its enormous fluffy tail around itself for warmth in mountain winters. Never roars; only purrs. Llamas in the high Andes sometimes share territory with them."},
  {"commonName":"Wolverine","sizeClass":"medium","fluffiness":6,"typicalDisposition":"tenacious","typicalLifespanYears":13,"classification":{"kingdom":"Animalia","phylum":"Chordata","class":"Mammalia","order":"Carnivora","family":"Mustelidae","genus":"Gulo","species":"Gulo gulo"},"description":"Has been documented driving bears off carcasses. Radiates absolute refusal. Llamas who keep them report a subtle improvement in their own personal boundaries."},
  {"commonName":"Sun Bear","sizeClass":"medium","fluffiness":4,"typicalDisposition":"curious","typicalLifespanYears":30,"classification":{"kingdom":"Animalia","phylum":"Chordata","class":"Mammalia","order":"Carnivora","family":"Ursidae","genus":"Helarctos","species":"Helarctos malayanus"},"description":"The world's smallest bear. Has a 25cm tongue for extracting honey. Llamas keep them primarily for the facial expressions."},
  {"commonName":"Giant Anteater","sizeClass":"large","fluffiness":4,"typicalDisposition":"purposeful","typicalLifespanYears":15,"classification":{"kingdom":"Animalia","phylum":"Chordata","class":"Mammalia","order":"Pilosa","family":"Myrmecophagidae","genus":"Myrmecophaga","species":"Myrmecophaga tridactyla"},"description":"Eats 35,000 ants and termites per day. Cannot chew anything. Has 4cm claws it folds under when walking. Llamas find its dedication to a single purpose admirable."},
  {"commonName":"Sloth","sizeClass":"medium","fluffiness":5,"typicalDisposition":"deliberate","typicalLifespanYears":30,"classification":{"kingdom":"Animalia","phylum":"Chordata","class":"Mammalia","order":"Pilosa","family":"Bradypodidae","genus":"Bradypus","species":"Bradypus tridactylus"},"description":"Moves so slowly that algae grows on its fur. Descends from trees once a week to defecate, a decision llamas consider respectably ritualistic."},
  {"commonName":"Aardvark","sizeClass":"large","fluffiness":2,"typicalDisposition":"determined","typicalLifespanYears":23,"classification":{"kingdom":"Animalia","phylum":"Chordata","class":"Mammalia","order":"Tubulidentata","family":"Orycteropodidae","genus":"Orycteropus","species":"Orycteropus afer"},"description":"The only living member of its order. Has a long sticky tongue. Digs faster than any other animal relative to its size. Alphabetically first in most llamaverse animal encyclopaedias, which it takes no pride in."},

  # ── CETACEANS ─────────────────────────────────────────────────────────────────
  {"commonName":"Blue Whale","sizeClass":"gigantic","fluffiness":1,"typicalDisposition":"immense","typicalLifespanYears":90,"classification":{"kingdom":"Animalia","phylum":"Chordata","class":"Mammalia","order":"Artiodactyla","family":"Balaenopteridae","genus":"Balaenoptera","species":"Balaenoptera musculus"},"description":"The largest animal that has ever lived. Its heart is the size of a small car. Llamas who keep them own entire private bays."},
  {"commonName":"Orca","sizeClass":"gigantic","fluffiness":2,"typicalDisposition":"strategic","typicalLifespanYears":90,"classification":{"kingdom":"Animalia","phylum":"Chordata","class":"Mammalia","order":"Artiodactyla","family":"Delphinidae","genus":"Orcinus","species":"Orcinus orca"},"description":"Has regional dialects. Teaches its young coordinated hunting techniques. Lives in matriarchal family groups. Llamas find the family dynamics familiar."},
  {"commonName":"Sperm Whale","sizeClass":"gigantic","fluffiness":1,"typicalDisposition":"deep","typicalLifespanYears":70,"classification":{"kingdom":"Animalia","phylum":"Chordata","class":"Mammalia","order":"Artiodactyla","family":"Physeteridae","genus":"Physeter","species":"Physeter macrocephalus"},"description":"Has the largest brain of any animal. Dives 2km deep. Sleeps vertically in groups near the surface. Llamas with access to deep ocean keep them and communicate via interpretive dance."},
  {"commonName":"Beluga Whale","sizeClass":"large","fluffiness":1,"typicalDisposition":"chatty","typicalLifespanYears":70,"classification":{"kingdom":"Animalia","phylum":"Chordata","class":"Mammalia","order":"Artiodactyla","family":"Monodontidae","genus":"Delphinapterus","species":"Delphinapterus leucas"},"description":"Called the 'canary of the sea' for its wide vocal range. Can change the shape of its forehead bulge (its melon) by moving air. Llamas who keep belugas report highly engaging conversations."},

  # ── PRIMATES ──────────────────────────────────────────────────────────────────
  {"commonName":"Proboscis Monkey","sizeClass":"medium","fluffiness":3,"typicalDisposition":"distinguished","typicalLifespanYears":20,"classification":{"kingdom":"Animalia","phylum":"Chordata","class":"Mammalia","order":"Primates","family":"Cercopithecidae","genus":"Nasalis","species":"Nasalis larvatus"},"description":"Has an enormously elongated nose. Males with larger noses are considered more attractive. Llamas appreciate the straightforward aesthetic criteria."},
  {"commonName":"Mandrill","sizeClass":"large","fluffiness":3,"typicalDisposition":"colourful","typicalLifespanYears":20,"classification":{"kingdom":"Animalia","phylum":"Chordata","class":"Mammalia","order":"Primates","family":"Cercopithecidae","genus":"Mandrillus","species":"Mandrillus sphinx"},"description":"Has a vivid blue and red face and multi-coloured hindquarters. The most vividly coloured mammal on earth. Llamas keep them for the visual interest."},
  {"commonName":"Slow Loris","sizeClass":"small","fluffiness":7,"typicalDisposition":"deliberate","typicalLifespanYears":20,"classification":{"kingdom":"Animalia","phylum":"Chordata","class":"Mammalia","order":"Primates","family":"Lorisidae","genus":"Nycticebus","species":"Nycticebus coucang"},"description":"Moves with extraordinary slowness. Its venom is activated by licking a gland on its arm. Llamas who keep them take the legal permitting process extremely seriously."},
  {"commonName":"Emperor Tamarin","sizeClass":"tiny","fluffiness":7,"typicalDisposition":"imperious","typicalLifespanYears":18,"classification":{"kingdom":"Animalia","phylum":"Chordata","class":"Mammalia","order":"Primates","family":"Callitrichidae","genus":"Saguinus","species":"Saguinus imperator"},"description":"Named after Kaiser Wilhelm II due to its magnificent white moustache. Weighs 500g. Llamas find the self-presentation impeccable at any scale."},
  {"commonName":"Tarsier","sizeClass":"tiny","fluffiness":4,"typicalDisposition":"wide-eyed","typicalLifespanYears":24,"classification":{"kingdom":"Animalia","phylum":"Chordata","class":"Mammalia","order":"Primates","family":"Tarsiidae","genus":"Cephalopachus","species":"Cephalopachus bancanus"},"description":"Eyes so large they cannot move them in their sockets. Can rotate its head 180 degrees. The most purely nocturnal primate. Llamas find the commitment to being awake at night solidarity-inducing."},

  # ── ADDITIONAL INVERTEBRATES & ODDITIES ──────────────────────────────────────
  {"commonName":"Giant Clam","sizeClass":"gigantic","fluffiness":1,"typicalDisposition":"immovable","typicalLifespanYears":100,"classification":{"kingdom":"Animalia","phylum":"Mollusca","class":"Bivalvia","order":"Cardiida","family":"Cardiidae","genus":"Tridacna","species":"Tridacna gigas"},"description":"Up to 1.2 metres across and 200kg. Filters hundreds of litres of water daily. Never moves after settling. Llamas find this level of commitment to a single location deeply calming."},
  {"commonName":"Coconut Crab","sizeClass":"large","fluffiness":1,"typicalDisposition":"determined","typicalLifespanYears":60,"classification":{"kingdom":"Animalia","phylum":"Arthropoda","class":"Malacostraca","order":"Decapoda","family":"Coenobitidae","genus":"Birgus","species":"Birgus latro"},"description":"The largest terrestrial invertebrate. Climbs trees, cracks coconuts, has been known to steal shiny objects including car keys. Llamas admire the entrepreneurial spirit."},
  {"commonName":"Pistol Shrimp","sizeClass":"tiny","fluffiness":1,"typicalDisposition":"explosive","typicalLifespanYears":4,"classification":{"kingdom":"Animalia","phylum":"Arthropoda","class":"Malacostraca","order":"Decapoda","family":"Alpheidae","genus":"Alpheus","species":"Alpheus heterochaelis"},"description":"Snaps its claw so fast it creates a cavitation bubble hotter than the sun's surface for a fraction of a second. Llamas keep them in very thick tanks."},
  {"commonName":"Mimic Octopus","sizeClass":"small","fluffiness":1,"typicalDisposition":"theatrical","typicalLifespanYears":1,"classification":{"kingdom":"Animalia","phylum":"Mollusca","class":"Cephalopoda","order":"Octopoda","family":"Octopodidae","genus":"Thaumoctopus","species":"Thaumoctopus mimicus"},"description":"Impersonates flatfish, lionfish, and sea snakes on demand. Llamas never quite know what they're looking at, which they find energising."},
  {"commonName":"Sea Cucumber","sizeClass":"small","fluffiness":1,"typicalDisposition":"passive","typicalLifespanYears":5,"classification":{"kingdom":"Animalia","phylum":"Echinodermata","class":"Holothuroidea","order":"Holothuriida","family":"Holothuriidae","genus":"Holothuria","species":"Holothuria scabra"},"description":"Breathes through its bottom. Ejects its internal organs when threatened, then regrows them. Llamas who keep them have learned not to startle them near the furniture."},
  {"commonName":"Crown-of-Thorns Starfish","sizeClass":"medium","fluffiness":1,"typicalDisposition":"relentless","typicalLifespanYears":8,"classification":{"kingdom":"Animalia","phylum":"Echinodermata","class":"Asteroidea","order":"Valvatida","family":"Acanthasteridae","genus":"Acanthaster","species":"Acanthaster planci"},"description":"40 arms covered in venomous spines. Eats coral. Has a taste for the dramatic. Llamas who keep them do so in isolation with good reason."},
  {"commonName":"Mantis Shrimp","sizeClass":"small","fluffiness":1,"typicalDisposition":"perceptive","typicalLifespanYears":6,"classification":{"kingdom":"Animalia","phylum":"Arthropoda","class":"Malacostraca","order":"Stomatopoda","family":"Gonodactylidae","genus":"Gonodactylus","species":"Gonodactylus smithii"},"description":"Sees 16 types of colour (humans see 3). Punches prey with 1500 newtons of force. Llamas sometimes worry that mantis shrimp may be more intelligent than they are."},
  {"commonName":"Tardigrade — Water Bear (Arctic)","sizeClass":"microscopic","fluffiness":1,"typicalDisposition":"enduring","typicalLifespanYears":3,"classification":{"kingdom":"Animalia","phylum":"Tardigrada","class":"Eutardigrada","order":"Apochela","family":"Milnesiidae","genus":"Milnesium","species":"Milnesium tardigradum"},"description":"An arctic variety of water bear capable of surviving in temperatures from -273°C to 151°C. Llamas who travel to extreme environments take them as companions. They survive everything."},
  {"commonName":"Peacock Spider","sizeClass":"microscopic","fluffiness":5,"typicalDisposition":"performative","typicalLifespanYears":1,"classification":{"kingdom":"Animalia","phylum":"Arthropoda","class":"Arachnida","order":"Araneae","family":"Salticidae","genus":"Maratus","species":"Maratus volans"},"description":"4mm long. The male fans out a vivid iridescent abdomen flap and performs an elaborate dance. Llamas keep them in observation boxes and watch the performances at great magnification. Angela has attended."},
  {"commonName":"Firefly","sizeClass":"tiny","fluffiness":1,"typicalDisposition":"romantic","typicalLifespanYears":2,"classification":{"kingdom":"Animalia","phylum":"Arthropoda","class":"Insecta","order":"Coleoptera","family":"Lampyridae","genus":"Photinus","species":"Photinus pyralis"},"description":"Each species has a unique light-flash pattern for attracting mates. Llamas keep meadows of them and the summer display is a major cultural event."},
  {"commonName":"Bombardier Beetle (Electric Blue)","sizeClass":"tiny","fluffiness":1,"typicalDisposition":"incandescent","typicalLifespanYears":2,"classification":{"kingdom":"Animalia","phylum":"Arthropoda","class":"Insecta","order":"Coleoptera","family":"Carabidae","genus":"Pheropsophus","species":"Pheropsophus jessoensis"},"description":"Asian variant of the bombardier beetle with vivid metallic blue elytra. Still fires boiling spray. The aesthetic upgrade makes llamas no less cautious."},
  {"commonName":"Acorn Barnacle","sizeClass":"microscopic","fluffiness":1,"typicalDisposition":"sessile","typicalLifespanYears":10,"classification":{"kingdom":"Animalia","phylum":"Arthropoda","class":"Thecostraca","order":"Sessilia","family":"Balanidae","genus":"Semibalanus","species":"Semibalanus balanoides"},"description":"Cements itself headfirst to a rock and spends its entire life waving food into its mouth. Llamas who keep them note that no motivation is required."},
  {"commonName":"Decorator Crab","sizeClass":"small","fluffiness":2,"typicalDisposition":"creative","typicalLifespanYears":3,"classification":{"kingdom":"Animalia","phylum":"Arthropoda","class":"Malacostraca","order":"Decapoda","family":"Majidae","genus":"Camposcia","species":"Camposcia retusa"},"description":"Attaches living sponges, algae, and other organisms to its shell as both camouflage and fashion. Llamas consider it the original bespoke couturier of the sea."},
  {"commonName":"Glaucus atlanticus (Blue Dragon Sea Slug)","sizeClass":"tiny","fluffiness":1,"typicalDisposition":"dramatic","typicalLifespanYears":1,"classification":{"kingdom":"Animalia","phylum":"Mollusca","class":"Gastropoda","order":"Nudibranchia","family":"Glaucidae","genus":"Glaucus","species":"Glaucus atlanticus"},"description":"3cm long, floats upside-down on the ocean surface, and is vivid silver-blue. Concentrates the sting cells of Portuguese man o' wars it eats and deploys them itself. Llamas consider it gloriously irresponsible."},
  {"commonName":"Mimic Octopus (second variant)","sizeClass":"small","fluffiness":1,"typicalDisposition":"shape-shifting","typicalLifespanYears":1,"classification":{"kingdom":"Animalia","phylum":"Mollusca","class":"Cephalopoda","order":"Octopoda","family":"Octopodidae","genus":"Wunderpus","species":"Wunderpus photogenicus"},"description":"Its name is Wunderpus photogenicus, which tells you everything you need to know. Its markings are unique to each individual. Llamas who keep them insist on formal portrait sessions."},
]

# Give every species a stable UUID based on its scientific name
for sp in SPECIES:
    name_key = sp["classification"]["species"].replace(" ","_")
    sp["id"] = str(uuid.uuid5(uuid.NAMESPACE_DNS, f"llamaverse.species.{name_key}"))

# ─────────────────────────────────────────────────────────────────────────────
# LLAMA-FRIENDLY NAMES  (pool to draw from)
# ─────────────────────────────────────────────────────────────────────────────
FIRST_NAMES = [
    "Biscuit","Pebble","Wobble","Crumble","Squiggles","Noodle","Fringe","Dazzle",
    "Crinkle","Bumble","Fizzle","Tangle","Snapper","Freckles","Pudding","Razzle",
    "Gloop","Shimmer","Bristle","Flicker","Munchkin","Tipple","Zippy","Wriggle",
    "Burble","Clatter","Sprocket","Jangle","Twizzle","Stumble","Floss","Gurgle",
    "Crumple","Wobblesworth","Snorkel","Grumble","Glimmer","Skitter","Twitch","Plonk",
    "Boggle","Squelch","Splodge","Fidget","Nudge","Shuffle","Pringle","Waggle","Kerfuffle",
    "Dimple","Crinkleworth","Swoopington","Blorpington","Flapdoodle","Snuffleby",
    "Noodlesworth","Bafflement","Quibbleston","Rumpus","Dingleberry","Flibbertigibbet",
    "Snickerdoodle","Widdershins","Brouhaha","Kerfuffle Jr","Bamboozle","Hullabaloo",
    "Gobsmack","Higgledy","Piggledy","Topsy","Turvy","Knick","Knack","Tintinnabulation",
]

QUIRKS = [
    "insists on a bedtime story every night",
    "has memorised all 88 Beethoven piano sonatas",
    "only eats food arranged in symmetrical patterns",
    "refuses to make eye contact but sends heartfelt letters",
    "has been learning to juggle for three years with no progress",
    "collects bottle caps from obscure regions",
    "sings exactly one note whenever startled",
    "is writing a novel but will not discuss the plot",
    "naps in increasingly creative locations",
    "has formed strong opinions about architecture",
    "stages elaborate fake emergencies to see who responds fastest",
    "only communicates using interpretive movement between 9 and 10am",
    "has memorised the bus timetable for a city it has never visited",
    "constructed a scale model of the hay festival from memory",
    "believes it is being followed, correctly",
    "refuses to acknowledge Mondays",
    "is training for a marathon at a very leisurely pace",
    "has attempted to file taxes three years in a row without opposable thumbs",
    "knows one card trick and performs it at every possible opportunity",
    "judges every piece of music against a private internal standard it has never revealed",
    "has been composing the same symphony for eleven years",
    "organises its food alphabetically before eating",
    "sleeps only in prime-numbered minutes",
    "has never once been surprised by anything",
    "maintains a written log of everything it finds interesting, which is everything",
]

DISPOSITIONS = [
    "curious","timid","regal","mischievous","serene","grumpy","affectionate",
    "hyperactive","lazy","theatrical","philosophical","cheerful","stoic","erratic",
    "dignified","sneaky","earnest","bombastic","aloof","devoted","eccentric",
]

# ─────────────────────────────────────────────────────────────────────────────
# GENERATE PETS  (~800 total — roughly 7 per species)
# ─────────────────────────────────────────────────────────────────────────────
# Llama owner IDs (from the llamaverse profiles — we'll just use names as references)
LLAMA_NAMES = [
    "Aaron","Angela","Ashley","Anthony","Bradley","Beatrice","Miranda","Fernanda",
    "Reginald","Alice","Boris","Clara","Derek","Elena","Freddie","Gwen","Horatio",
    "Isolde","Jasper","Kestrel","Lorenzo","Monique","Nigel","Ophelia","Percy",
]

pets = []
for species in SPECIES:
    n_pets = random.randint(5, 9)
    for i in range(n_pets):
        name = random.choice(FIRST_NAMES)
        age = random.randint(0, max(1, int(species["typicalLifespanYears"] * 0.8)))
        pets.append({
            "id": str(uuid.uuid4()),
            "name": name,
            "ageYears": age,
            "disposition": random.choice(DISPOSITIONS),
            "fluffiness": max(1, min(10, species["fluffiness"] + random.randint(-1, 1))),
            "quirk": random.choice(QUIRKS),
            "speciesId": species["id"],
            "speciesCommonName": species["commonName"],
            "speciesScientificName": species["classification"]["species"],
            "sizeClass": species["sizeClass"],
            "ownerName": random.choice(LLAMA_NAMES),
        })

# ─────────────────────────────────────────────────────────────────────────────
# ANIMAL SHELTERS
# ─────────────────────────────────────────────────────────────────────────────
SHELTER_DATA = [
    {"name":"The Wandering Fleece Animal Sanctuary","location":"Northern Highlands","specialties":["microscopic","tiny"],"description":"The llamaverse's premier specialist shelter for microscopic and tiny animals. Has 47 microscopes available for public viewing. Famous for its annual Tardigrade Day event, which draws 8,000 visitors. Staff are deeply committed and extremely patient."},
    {"name":"Fernanda's Home for Misunderstood Creatures","location":"Silicon Meadow, Andes Region","specialties":["small","medium"],"description":"Founded by Dr Fernanda after rescuing a blobfish from a laboratory. Specialises in animals with unfortunate reputations — bombardier beetles, hissing cockroaches, vinegaroons. The ethos is radical non-judgement."},
    {"name":"The Patagonian Wild Wing Refuge","location":"Southern Patagonia","specialties":["large","gigantic"],"description":"An open-sky sanctuary for large birds and megafauna. The grounds cover 400 hectares. Angela is a patron and has performed a leaf-dancing dedication ceremony at every annual gala since 2019."},
    {"name":"Deep Blue Creature Sanctuary","location":"Coastal Llamaville","specialties":["aquatic","gigantic"],"description":"Specialises in marine animals from sea cucumbers to belugas. Has a private bay for cetacean residents. Runs the only llamaverse certification programme in marine mammal care."},
    {"name":"The Quiet Pool","location":"Cusco, Peru Region","specialties":["microscopic","aquatic"],"description":"A contemplative sanctuary where every animal is aquatic or microscopic. Visitors enter in silence. Known for its research programme into freshwater hydra longevity, in partnership with the Llamaverse Institute of Technology."},
    {"name":"Bradley's Extreme Fauna Compound","location":"LIT Research Campus, Andes Region","specialties":["large","gigantic","dangerous"],"description":"Not technically open to the public. Bradley established it as a research facility. Animals include a coconut crab that has escaped four times, a cassowary that has not, and a goliath birdeater named 'Hypothesis' that is being studied for web-strength applications."},
    {"name":"The Cosy Burrow Rescue and Rehoming","location":"Llamaville Central District","specialties":["small","medium","fluffy"],"description":"Specialises in fluffy and burrowing mammals — fennec foxes, chinchillas, red pandas, arctic foxes. The waiting list for adopting a red panda is currently 14 months. The shelter newsletter has 40,000 subscribers."},
    {"name":"The Archipelago Orphanage","location":"Eastern Coastal Islands","specialties":["aquatic","small"],"description":"Rescues and rehomes sea creatures. Particularly known for its octopus enclosures, which are rebuilt monthly when the octopi inevitably escape and improve them. The facility has a standing bet with the octopi, which the octopi are winning."},
    {"name":"The Stillness Institute","location":"Northern Tundra","specialties":["arctic","large","gigantic"],"description":"Cares for arctic and sub-arctic megafauna. Home to the only captive narwhal in the llamaverse, on long-term loan from the government. The resident snow leopards have full run of the tundra grounds."},
    {"name":"The Peculiar Menagerie of Llamaville East","location":"Eastern Llamaville","specialties":["eccentric","unusual","rare"],"description":"Founded on the principle that the strangest animals deserve the most attention. Home to a mata mata turtle, three axolotls, a vampire squid, and one animal the management refuses to identify. Visitor numbers are highest on the days when the mystery animal is active."},
    {"name":"The Wool and Scales Rehabilitation Centre","location":"WoolWorks Campus, Northern Highlands","specialties":["reptile","mammal"],"description":"A joint initiative of WoolWorks International and the llamaverse government. Rehabilitates reptiles and small mammals displaced by habitat development. The wool genomics lab upstairs has contributed significantly to understanding reptile thermoregulation."},
    {"name":"The Old Pond Sanctuary","location":"Rural Southern District","specialties":["amphibian","aquatic"],"description":"Exclusively for amphibians. 140 different species in residence. The hellbender programme is internationally recognised. Staff wear rubber gloves for all interactions, a policy introduced after the surinam toad incident of 2022 which no one will discuss in detail."},
    {"name":"Apex Companions Forever","location":"Capital Meadow","specialties":["exotic","large","companion"],"description":"A premium rehoming service for the llamaverse's highest-status pets. Provides Komodo dragons, harpy eagles, giant pacific octopi, and similar to approved llama adopters. The vetting process takes six months. Operates at the apex of the apex."},
    {"name":"The Galaxy of Small Things","location":"Llamaville Arts Quarter","specialties":["microscopic","tiny","artistic"],"description":"Part shelter, part public exhibition. All residents are tiny or microscopic, displayed in illuminated cases with educational panels. Angela curated the introductory installation. Voted the most unusual night out in Llamaville three years running."},
    {"name":"Primate House of the Andes","location":"Andean Foothills","specialties":["primate","small","medium"],"description":"The only shelter in the llamaverse specialising exclusively in primates. Cares for tarsiers, emperor tamarins, slow lorises, and aye-ayes. Has a strict no-photography policy to protect the slow lorises from overstimulation."},
]

shelters = []
random.shuffle(pets)
pets_per_shelter = len(pets) // len(SHELTER_DATA)
for i, sd in enumerate(SHELTER_DATA):
    shelter_pets = pets[i*pets_per_shelter : (i+1)*pets_per_shelter]
    shelters.append({
        "id": str(uuid.uuid5(uuid.NAMESPACE_DNS, f"llamaverse.shelter.{sd['name']}")),
        "name": sd["name"],
        "location": sd["location"],
        "specialties": sd["specialties"],
        "description": sd["description"],
        "capacity": 30 + random.randint(0,120),
        "currentResidentCount": len(shelter_pets),
        "availablePetIds": [p["id"] for p in shelter_pets],
    })
    for p in shelter_pets:
        p["shelterId"] = shelters[-1]["id"]
        p["shelterName"] = sd["name"]

# ─────────────────────────────────────────────────────────────────────────────
# WRITE EVERYTHING
# ─────────────────────────────────────────────────────────────────────────────
def write_docs(content_type, docs, collections):
    dir_path = os.path.join(BASE, content_type)
    os.makedirs(dir_path, exist_ok=True)
    with open(os.path.join(dir_path, "collections.properties"), "w") as f:
        f.write(f"*={','.join(collections)}\n")
    for doc in docs:
        envelope = {"envelope": {"headers": {"type": content_type}, "instance": {content_type: doc}}}
        with open(os.path.join(dir_path, f"{doc['id']}.json"), "w") as f:
            json.dump(envelope, f, indent=2)
    print(f"  {len(docs)} {content_type} docs -> {dir_path}")

print("Generating llamaverse animal content...")
write_docs("animal-species", SPECIES, ["llamaverse","content","animal-species"])
write_docs("pets", pets, ["llamaverse","content","pets"])
write_docs("animal-shelters", shelters, ["llamaverse","content","animal-shelters"])
print(f"Total: {len(SPECIES)} species, {len(pets)} pets, {len(shelters)} shelters")
print("Done. Run ./gradlew mlLoadData to deploy.")
